### PR TITLE
Add AMD & Common JS support so lib can be used with Node & Browserify

### PR DESCRIPTION
**Pull request by mrmartineau**
it would be great if you add this script to NPM as well..

### CODE REVIEW

**Comment by mrmartineau** [comment]
Any news on this..?

**Comment by alfredxing** [comment]
@mrmartineau Sorry! For some reason I wasn't watching the repo. I'm not super familiar with AMD or Browserify, but from what I know it looks good to me.

Thanks for the PR!

**Comment by mrmartineau** [comment]
that's no problem, it happens to me as well sometimes. Could you add this to NPM as well? https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by alfredxing** [comment]
@mrmartineau Sure, I'll look into it. Can you open up a new issue for that, so I don't forget about it? Thanks!

**Pull request merged**
